baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Massively'
disableKinds = ['taxonomy', 'term']

[params]
  description = "A free, fully responsive HTML5 + CSS3 site template designed by @ajlkn for HTML5 UP"
  author = "HTML5 UP"

  # Social media links
  [params.social]
    twitter = "#"
    facebook = "#"
    instagram = "#"
    github = "#"

  # Contact information
  [params.contact]
    address = "1234 Somewhere Road #87257<br />Nashville, TN 00000-0000"
    phone = "(000) 000-0000"
    email = "info@untitled.tld"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    identifier = "tailwind-demo"
    name = "Tailwind Demo"
    url = "/tailwind-demo/"
    weight = 4
  [[menu.main]]
    identifier = "eslint-demo"
    name = "ESLint Demo"
    url = "/eslint-demo/"
    weight = 5
  [[menu.main]]
    identifier = "prettier-demo"
    name = "Prettier Demo"
    url = "/prettier-demo/"
    weight = 6